# Generated by Django 4.0.4 on 2022-05-10 21:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[А-ЯЁ][а-яё]+')], verbose_name='Имя студента')),
                ('surname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[А-ЯЁ][а-яё]+')], verbose_name='Фамилия студента')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[А-ЯЁ][а-яё]+')], verbose_name='Имя преподаватель')),
                ('teacher_surname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[А-ЯЁ][а-яё]+')], verbose_name='Фамилия преподавателя')),
                ('teacher_patronymic', models.CharField(help_text='Если имеется', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[А-ЯЁ][а-яё]+')], verbose_name='Отчество преподавателя')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(verbose_name='Оценка за предмет')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выставления оценки')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.lesson', verbose_name='Предмет')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.student', verbose_name='Студент')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.teacher', verbose_name='Преподаватель'),
        ),
    ]
