# Generated by Django 4.0.4 on 2022-05-10 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_patronymic',
            field=models.CharField(blank=True, help_text='Если имеется', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[А-ЯЁ][а-яё]+')], verbose_name='Отчество преподавателя'),
        ),
    ]
